mlflow:
  experiment_name: proto
  run_name: initial_proto
train:
  epochs: 10
  batch_size: 2
  save_steps: 2
  random_seed: 19
  shots: 20480
  model_output_dir: models/20240827_proto
  model_name: model_name_proto
  processed_data_filename: processed_data_filename_proto
  processed_data_output_dir: data/processed_data_output_dir_proto
model:
  quanv_kernel_size: [3, 3]
  quanv_num_filters: 3
  quanv_padding_mode: "constant"
